M48
; DRILL file KiCad 10.0.3-10.0.3~ubuntu24.04.1 date 2026-06-03T11:59:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-03T11:59:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3-10.0.3~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X195.96Y-103.72
X201.74Y-103.72
M30
